/**
 * Builds the canonical data-platform artifacts from the research directory:
 *
 *   data-platform/out/canonical.json  — full canonical snapshot (companies,
 *                                        licences, funding, evidence, sources)
 *   data-platform/out/coverage.json   — coverage stats
 *   data-platform/out/seed.sql        — PostgreSQL seed matching database/schema.sql
 *
 * Run via `npm run platform:import`. Contract tests in
 * src/__tests__/data-platform.test.ts guard the import rules.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parseEnrichedDirectory } from "../src/lib/india-directory-parse";
import { RADAR_LICENCES, RADAR_LICENCE_LABELS } from "../src/lib/radar-facets";
import { collectCategoryIds, categoryId, coverageStats, importDirectory, mapCompanyStatus } from "../src/data-platform/import-directory";
import { RESEARCH_COMPILED_AT } from "../src/data-platform/sources";
import type { CompanyRecord, Confidence } from "../src/data-platform/types";

const markdownPath = resolve(process.cwd(), "docs/research/india-fintech-directory-enriched.md");
const outDir = resolve(process.cwd(), "data-platform/out");
const schemaPath = resolve(process.cwd(), "database/schema.sql");

const records = parseEnrichedDirectory(readFileSync(markdownPath, "utf8"));
const snapshot = importDirectory(records);
const coverage = coverageStats(snapshot);

function sqlStr(value: string | undefined | null): string {
  if (value === undefined || value === null) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlOptNum(value: number | undefined | null): string {
  if (value === undefined || value === null) return "NULL";
  return String(value);
}

function sqlOptDate(value: string | undefined | null): string {
  return sqlStr(value ?? null);
}

function buildSeed(snapshotData: ReturnType<typeof importDirectory>): string {
  const lines: string[] = [];
  lines.push("-- ============================================================================");
  lines.push("-- Seed data for the FinTech Atlas Radar data platform (ADR-002).");
  lines.push("-- Generated by scripts/build-data-platform.ts from the research directory.");
  lines.push("-- Load against database/schema.sql (PostgreSQL).");
  lines.push("-- ============================================================================");
  lines.push("");

  const { sources, records: recs } = snapshotData;

  lines.push("INSERT INTO regulators (code, name) VALUES");
  lines.push(
    [
      "('RBI', 'Reserve Bank of India')",
      "('SEBI', 'Securities and Exchange Board of India')",
      "('IRDAI', 'Insurance Regulatory and Development Authority of India')",
      "('NPCI', 'National Payments Corporation of India')",
      "('FIU', 'Financial Intelligence Unit')",
      "('mixed', 'Mixed / multiple regulators')",
    ].join(",\n"),
  );
  lines.push(";");
  lines.push("");

  lines.push("INSERT INTO licenses (code, label, regulator) VALUES");
  lines.push(
    RADAR_LICENCES.map((code) => `(${sqlStr(code)}, ${sqlStr(RADAR_LICENCE_LABELS[code])}, 'RBI')`).join(",\n"),
  );
  lines.push(";");
  lines.push("");

  lines.push("INSERT INTO sources (id, url, publisher, source_type, accessed_at, effective_at) VALUES");
  lines.push(
    sources
      .map((s) =>
        `(${sqlStr(s.id)}, ${sqlStr(s.url)}, ${sqlStr(s.publisher)}, ${sqlStr(s.sourceType)}, ${sqlStr(s.accessedAt)}, ${sqlOptDate(s.effectiveAt)})`,
      )
      .join(",\n"),
  );
  lines.push(";");
  lines.push("");

  const categories = collectCategoryIds(
    recs.flatMap((r) => [r.company.category, ...r.categories.map((c) => c.category)]),
  );
  lines.push("INSERT INTO categories (id, label) VALUES");
  lines.push([...categories].map(([id, label]) => `(${sqlStr(id)}, ${sqlStr(label)})`).join(",\n"));
  lines.push(";");
  lines.push("");

  lines.push("INSERT INTO companies (id, legal_name, display_name, website, description, founded_year, headquarters_city, status) VALUES");
  lines.push(
    recs
      .map((r) =>
        `(${sqlStr(r.company.id)}, ${sqlStr(r.company.legalName)}, ${sqlStr(r.company.displayName)}, ${sqlStr(r.company.website)}, ${sqlStr(r.company.description)}, ${sqlOptNum(r.company.foundedYear)}, ${sqlStr(r.company.headquarters)}, ${sqlStr(mapCompanyStatus(r.company.status))})`,
      )
      .join(",\n"),
  );
  lines.push(";");
  lines.push("");

  const seenCategories = new Set<string>();
  lines.push("INSERT INTO company_categories (company_id, category_id, source_id, confidence, verified_at) VALUES");
  lines.push(
    recs
      .flatMap((r) => r.categories.map((c) => ({ companyId: c.companyId, category: c.category, sourceId: c.sourceId, confidence: c.confidence })))
      .filter((c) => {
        const key = `${c.companyId}|${categoryId(c.category)}`;
        if (seenCategories.has(key)) return false;
        seenCategories.add(key);
        return true;
      })
      .map((c) =>
        `(${sqlStr(c.companyId)}, ${sqlStr(categoryId(c.category))}, ${sqlStr(c.sourceId)}, ${sqlStr(c.confidence)}, ${sqlStr(RESEARCH_COMPILED_AT)})`,
      )
      .join(",\n"),
  );
  lines.push(";");
  lines.push("");

  const licenceRows = recs.flatMap((r) => r.licences);
  if (licenceRows.length > 0) {
    lines.push("INSERT INTO company_licenses (company_id, license_id, regulator_id, status, effective_at, source_id, confidence, verified_at, notes) VALUES");
    lines.push(
      licenceRows.map((l) =>
        `(${sqlStr(l.companyId)}, ${sqlStr(l.code)}, ${sqlStr(l.regulator)}, ${sqlStr(l.status)}, ${sqlOptDate(l.effectiveDate)}, ${sqlStr(l.sourceId)}, ${sqlStr(l.confidence)}, ${sqlStr(l.verifiedAt)}, ${sqlStr(l.notes)})`,
      ).join(",\n"),
    );
    lines.push(";");
    lines.push("");
  }

  const fundingRows = recs.flatMap((r) => r.funding);
  if (fundingRows.length > 0) {
    lines.push("INSERT INTO funding_rounds (company_id, amount_usd_m, source_id, confidence, verified_at) VALUES");
    lines.push(
      fundingRows.map((f) =>
        `(${sqlStr(f.companyId)}, ${sqlOptNum(f.totalUsdM)}, ${sqlStr(f.sourceId)}, ${sqlStr(f.confidence)}, ${sqlStr(f.verifiedAt)})`,
      ).join(",\n"),
    );
    lines.push(";");
    lines.push("");
  }

  const evidenceRows = recs.flatMap((r) => r.evidence);
  lines.push("INSERT INTO evidence (company_id, field_name, value, source_id, confidence, verified_at, effective_at, notes) VALUES");
  lines.push(
    evidenceRows.map((e) =>
      `(${sqlStr(e.companyId)}, ${sqlStr(e.fieldName)}, ${sqlStr(e.value)}, ${sqlStr(e.sourceId)}, ${sqlStr(e.confidence as Confidence)}, ${sqlStr(e.verifiedAt)}, ${sqlOptDate(e.effectiveAt)}, ${sqlStr(e.notes)})`,
    ).join(",\n"),
  );
  lines.push(";");
  lines.push("");

  void (recs satisfies CompanyRecord[]);
  return lines.join("\n");
}

mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, "canonical.json"), JSON.stringify(snapshot, null, 2));
writeFileSync(resolve(outDir, "coverage.json"), JSON.stringify(coverage, null, 2));
writeFileSync(resolve(outDir, "seed.sql"), buildSeed(snapshot) + "\n");

console.log(
  `Built data-platform: ${coverage.companies} companies, ${coverage.licences} licences, ${coverage.evidenceRows} evidence rows.`,
);
console.log(`  canonical.json  → ${resolve(outDir, "canonical.json")}`);
console.log(`  coverage.json   → ${resolve(outDir, "coverage.json")}`);
console.log(`  seed.sql        → ${resolve(outDir, "seed.sql")}`);
console.log(`  schema reference: ${schemaPath}`);