// AUTO-GENERATED by scripts/fetch-logos.ts — do not edit by hand.
// Slugs that have a real official brand SVG at public/logos/<slug>.svg.
//
// Tiles are FIXED per theme, never derived from the page surface:
//   bg        : brand-correct field (Wise dark green, Brex orange) where the
//               simple-icons glyph is itself a brand colour.
//   tile:"ink": bright glyph on the fixed #23201a ink chip.
//   tile:"light": dark glyph on the fixed #ffffff chip.
//
// The rule is purely the glyph's own luminance against that fixed pair, so a
// mark cannot be legible in the light theme and invisible in the dark one.
// Previously "dark" resolved to --surface-raised, which flips from cream to
// near-black between themes; that left 16 of 37 marks under 3:1 in one theme,
// and Wise at exactly 1.00 (a #9FE870 glyph on a #9FE870 tile).
export const REAL_LOGOS: Record<string, { bg?: string; tile?: "light" | "ink" }> = {
  "adp": { "tile": "light" },
  "adyen": { "tile": "ink" },
  "afterpay": { "tile": "ink" },
  "apple-pay": { "tile": "light" },
  "binance": { "tile": "ink" },
  "braintree": { "tile": "light" },
  "brex": { "bg": "#FF5C00" },
  "bunq": { "tile": "light" },
  "cash-app": { "tile": "ink" },
  "circle": { "tile": "light" },
  "coinbase": { "tile": "light" },
  "google-pay": { "tile": "light" },
  "gusto": { "tile": "light" },
  "klarna": { "tile": "ink" },
  "mastercard-send": { "tile": "light" },
  "mercado-pago": { "tile": "ink" },
  "moneygram": { "tile": "light" },
  "monzo": { "tile": "light" },
  "n26": { "tile": "ink" },
  "nubank": { "tile": "light" },
  "okx": { "tile": "light" },
  "paychex": { "tile": "light" },
  "payoneer": { "tile": "light" },
  "paypal": { "tile": "light" },
  "paytm": { "tile": "light" },
  "phonepe": { "tile": "light" },
  "picpay": { "tile": "ink" },
  "razorpay": { "tile": "light" },
  "relay": { "tile": "light" },
  "revolut": { "tile": "light" },
  "robinhood": { "tile": "ink" },
  "square": { "tile": "light" },
  "starling": { "tile": "light" },
  "stripe": { "tile": "light" },
  "venmo": { "tile": "light" },
  "visa-direct": { "tile": "light" },
  "wise": { "bg": "#163300" },
};
