/**
 * Brand mark for each company.
 *
 * Two tiers of fidelity:
 *  1. REAL official mark — when `REAL_LOGOS[slug]` is set (generated by
 *     scripts/fetch-logos.ts from simple-icons), render the actual brand SVG
 *     from /logos/<slug>.svg on a tile chosen for legibility:
 *       - `bg`  → branded surface (Apple Pay black, Wise green, Klarna pink…)
 *       - `tile: "light"` → white inset mini-tile for dark-fill marks
 *       - `tile: "dark"`  → dark neutral surface for bright marks
 *  2. Inline fallback — `logoShapes` below: a geometric mark inspired by the
 *     official logo, rendered inline with the brand color. Used for every
 *     brand simple-icons doesn't carry. A monogram fallback covers any slug
 *     with no shape at all.
 */

import { REAL_LOGOS } from "@/data/logos-index";

export type Logo = { color: string; bg?: string; svg: string };

/**
 * Hand-drawn inline brand marks. Exported so tests can assert invariant
 * properties (e.g. dark-mode legibility) on the same data the component uses.
 */
export const logoShapes: Record<string, Logo> = {
  // ── Payments ──
  stripe: {
    color: "#635BFF",
    svg: `<rect x="6" y="4" width="28" height="32" rx="6" fill="currentColor" opacity="0.15"/><path d="M16 13c0-2 1.6-3 4-3s5 .8 5 .8l1.2-7S23.8 3 20.5 3C15.3 3 9 5.8 9 13.4c0 4.6 4 6.6 7 7.9 3 1.3 4 2 4 3.3 0 1.6-1.6 2.4-4 2.4-3.2 0-6-1.6-6-1.6L9 32s2.8 1.8 8 1.8c6 0 10.4-2.8 10.4-8.8 0-4.8-4.2-6.8-7.2-8-3-1.2-4.2-1.8-4.2-3 0-1 1.8-1.4 4-1.4z" fill="currentColor"/>`,
  },
  paypal: {
    color: "#003087",
    svg: `<path d="M12 6h10c5 0 8 3 7.4 7.4C28.6 18 24 21 19 21h-5l-1.6 9H7L12 6z" fill="#003087"/><path d="M16.4 12.5l-1.6 8.4h4c3.4 0 6-1.8 6.6-4.6.4-2.2-1.2-3.8-3.8-3.8h-2.4z" fill="#009CDE"/>`,
  },
  adyen: {
    color: "#0ABF53",
    svg: `<circle cx="20" cy="20" r="14" fill="currentColor"/><path d="M13 20h14M20 13v14" stroke="#0f0f14" stroke-width="2.5" stroke-linecap="round"/>`,
  },
  square: {
    color: "#3E3E40",
    svg: `<rect x="6" y="6" width="28" height="28" rx="5" fill="none" stroke="currentColor" stroke-width="3"/><rect x="13" y="13" width="14" height="14" rx="2" fill="currentColor"/>`,
  },
  block: {
    // Black mark; pin to white so the inner `--background` cutout resolves to
    // a visible dark square on a light tile (stays legible in dark mode).
    color: "#0F0F0F",
    bg: "#ffffff",
    svg: `<rect x="6" y="6" width="28" height="28" rx="6" fill="currentColor"/><rect x="13" y="13" width="14" height="14" rx="2.5" fill="var(--background, #08080a)"/>`,
  },
  braintree: {
    // Black mark; pin to white so the fallback matches the real-logo `tile:
    // "light"` treatment and stays visible in dark mode.
    color: "#000000",
    bg: "#ffffff",
    svg: `<circle cx="20" cy="20" r="13" fill="none" stroke="currentColor" stroke-width="3"/><path d="M20 8v24M8 20h24" stroke="currentColor" stroke-width="2.5" opacity="0.45"/><circle cx="20" cy="20" r="4" fill="currentColor"/>`,
  },
  worldpay: {
    color: "#E6007A",
    svg: `<circle cx="20" cy="20" r="14" fill="currentColor"/><path d="M8 22l6-6 4 4 6-8 4 4" stroke="#fff" stroke-width="2.2" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  "checkout-com": {
    color: "#4D5BFF",
    svg: `<circle cx="20" cy="20" r="13" fill="none" stroke="currentColor" stroke-width="3"/><path d="M20 7v26M7 20h26" stroke="currentColor" stroke-width="2.2" opacity="0.4"/><circle cx="20" cy="20" r="5" fill="currentColor"/>`,
  },
  klarna: {
    color: "#171A6B",
    svg: `<rect x="5" y="5" width="30" height="30" rx="8" fill="currentColor"/><text x="20" y="26" text-anchor="middle" font-family="monospace" font-size="14" font-weight="700" fill="#fff">K</text>`,
  },
  affirm: {
    color: "#0ACFEB",
    svg: `<rect x="6" y="6" width="28" height="28" rx="8" fill="none" stroke="currentColor" stroke-width="3"/><path d="M13 21l4 4 10-10" stroke="currentColor" stroke-width="3.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  afterpay: {
    // Black chevrons; pin to white to match the real-logo `tile: "dark"` →
    // mark-on-light presentation and stay visible in dark mode.
    color: "#000000",
    bg: "#ffffff",
    svg: `<path d="M8 14l6-2 6 4-6 4-6-2zM20 14l6-2 6 4-6 4-6-2z" fill="currentColor" opacity="0.9"/>`,
  },
  razorpay: {
    color: "#3395FF",
    svg: `<path d="M11 6c-3 8-5 16-5 20l4-14c4-1 9-1 11 4l3 14-3-6c-2-4-6-6-10-6h-2l3-12h-1z" fill="currentColor"/>`,
  },
  mollie: {
    color: "#000000",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><circle cx="20" cy="20" r="6" fill="#fff"/><circle cx="14" cy="14" r="2" fill="currentColor"/><circle cx="26" cy="14" r="2" fill="currentColor"/>`,
  },
  payu: {
    color: "#6BE226",
    svg: `<rect x="6" y="6" width="28" height="28" rx="4" fill="currentColor" opacity="0.18"/><path d="M14 12v16c0 3 2 4 5 4M14 18h8c2 0 3-1 3-3s-1-3-3-3h-8" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },

  // ── Neobanks ──
  chime: {
    color: "#1DC078",
    svg: `<path d="M20 5l12 6v6c0 7-5 12-12 15C13 29 8 24 8 17v-6l12-6z" fill="currentColor"/><path d="M16 18l3 3 5-6" stroke="#fff" stroke-width="2.2" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  revolut: {
    color: "#0075EB",
    svg: `<rect x="5" y="5" width="30" height="30" rx="8" fill="currentColor"/><path d="M14 13l5 7 5-7M16 13h6v3" stroke="#fff" stroke-width="2.4" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  nubank: {
    color: "#820AD1",
    svg: `<rect x="5" y="5" width="30" height="30" rx="8" fill="currentColor"/><path d="M13 12v8a7 7 0 0014 0v-2" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round"/>`,
  },
  monzo: {
    color: "#14233F",
    svg: `<path d="M9 8l11 9 11-9M9 8v18l11 6 11-6V8" fill="none" stroke="currentColor" stroke-width="3" stroke-linejoin="round"/><path d="M20 17v15" stroke="#E83B8B" stroke-width="3"/>`,
  },
  n26: {
    color: "#2DB5CF",
    svg: `<rect x="5" y="9" width="30" height="22" rx="3" fill="currentColor"/><path d="M13 16l7 8 7-8" stroke="#fff" stroke-width="2.4" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  starling: {
    color: "#5E2EFF",
    svg: `<circle cx="20" cy="20" r="13" fill="none" stroke="currentColor" stroke-width="3"/><path d="M14 16l3 5 6 1-5 3v2l-4-5-5-1z" fill="currentColor"/>`,
  },
  current: {
    color: "#00D4FF",
    svg: `<rect x="5" y="11" width="30" height="18" rx="4" fill="currentColor"/><path d="M9 20h22l-3-3 3 3-3 3" stroke="#0a0a0a" stroke-width="2.2" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  varo: {
    color: "#00D2A8",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M14 16l6 8 6-8" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  sofi: {
    color: "#0ACF83",
    svg: `<circle cx="20" cy="20" r="13" fill="none" stroke="currentColor" stroke-width="3"/><path d="M14 18a4 4 0 016-3 4 4 0 016 3c0 4-6 6-6 6s-6-2-6-6z" fill="currentColor"/>`,
  },
  ally: {
    color: "#6E2585",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M14 20c3 3 9 3 12 0" stroke="#fff" stroke-width="3" fill="none" stroke-linecap="round"/>`,
  },

  // ── Investing ──
  robinhood: {
    color: "#00C805",
    svg: `<path d="M8 32L20 8l12 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linejoin="round"/><path d="M20 8v6l-6 12" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/>`,
  },
  coinbase: {
    color: "#0052FF",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><circle cx="20" cy="20" r="5.5" fill="none" stroke="#fff" stroke-width="2.5"/>`,
  },
  freetrade: {
    color: "#FF5C00",
    svg: `<circle cx="20" cy="20" r="13" fill="none" stroke="currentColor" stroke-width="3"/><path d="M13 24l7-7 5 4 4-9" stroke="currentColor" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  wealthfront: {
    color: "#27E5A1",
    svg: `<rect x="6" y="6" width="28" height="28" rx="6" fill="currentColor"/><path d="M13 24l6-12 6 7 4-3" stroke="#0a0a0a" stroke-width="2.4" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  betterment: {
    color: "#FF8A00",
    svg: `<circle cx="20" cy="20" r="13" fill="none" stroke="currentColor" stroke-width="3"/><path d="M20 11v9l6 4" stroke="currentColor" stroke-width="2.6" fill="none" stroke-linecap="round"/>`,
  },
  public: {
    color: "#21CF7B",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M20 11l3 5 5 1-3.5 4 1 5.5L20 24l-5.5 2.5 1-5.5L12 17l5-1z" fill="#0a0a0a"/>`,
  },
  etoro: {
    color: "#00A4FF",
    svg: `<circle cx="20" cy="20" r="4" fill="currentColor"/><circle cx="13" cy="14" r="3" fill="currentColor"/><circle cx="27" cy="14" r="3" fill="currentColor"/><circle cx="14" cy="27" r="3" fill="currentColor"/><circle cx="26" cy="27" r="3" fill="currentColor"/>`,
  },
  stash: {
    color: "#25C7FF",
    svg: `<rect x="6" y="6" width="28" height="28" rx="6" fill="currentColor"/><path d="M14 16l4 4 8-8" stroke="#0a0a0a" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  acorns: {
    color: "#3CC780",
    svg: `<circle cx="20" cy="22" r="7" fill="currentColor"/><path d="M14 13a6 6 0 0112 0" stroke="currentColor" stroke-width="2.8" fill="none" stroke-linecap="round"/><circle cx="20" cy="22" r="2.5" fill="#0a0a0a"/>`,
  },
  fidelity: {
    color: "#74B53C",
    svg: `<path d="M8 22c0-6 5-10 12-10s12 4 12 10-5 8-12 8-12-2-12-8z" fill="currentColor"/><path d="M14 22c0-3 3-5 6-5s6 2 6 5-3 4-6 4-6-1-6-4z" fill="#fff"/>`,
  },


  // ── Cross-Border ──
  wise: {
    color: "#163300",
    bg: "#9FE870",
    svg: `<rect x="5" y="5" width="30" height="30" rx="8" fill="#9FE870"/><path d="M12 15v8h6l4-8h6l-4 8v8" stroke="#163300" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  remitly: {
    color: "#0099F2",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M20 13v14M14 18l6 6 6-6" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  xe: {
    color: "#1976D2",
    svg: `<rect x="5" y="5" width="30" height="30" rx="6" fill="currentColor"/><path d="M12 14l8 12M28 14l-8 12M14 14h-3v-1h11M26 26h3v1H18" stroke="#fff" stroke-width="2.2" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  ofx: {
    color: "#00B2A9",
    svg: `<circle cx="20" cy="20" r="13" fill="none" stroke="currentColor" stroke-width="3"/><path d="M14 14h12l-6 12" fill="currentColor" opacity="0.3"/><path d="M14 14h12l-6 12z" stroke="currentColor" stroke-width="2.6" fill="none" stroke-linejoin="round"/>`,
  },
  moneygram: {
    color: "#E40520",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><circle cx="20" cy="16" r="4" fill="none" stroke="#fff" stroke-width="2.2"/><path d="M13 28a7 7 0 0114 0" stroke="#fff" stroke-width="2.2" fill="none"/>`,
  },

  // ── BNPL ──
  zip: {
    // Zip's mark is black chevrons; on the neutral dark tile it vanishes, so
    // pin it to a white surface (mirrors REAL_LOGOS `tile: "light"`).
    color: "#1A1A1A",
    bg: "#ffffff",
    svg: `<path d="M9 8h11l-5 16h11" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round"/><circle cx="30" cy="11" r="2.5" fill="currentColor"/>`,
  },
  sezzle: {
    color: "#E6007A",
    svg: `<circle cx="14" cy="20" r="4" fill="currentColor" opacity="0.4"/><circle cx="20" cy="20" r="4" fill="currentColor" opacity="0.6"/><circle cx="26" cy="20" r="4" fill="currentColor"/><circle cx="32" cy="20" r="3" fill="currentColor" opacity="0.8"/>`,
  },
  splitit: {
    color: "#4E4DE4",
    svg: `<rect x="8" y="9" width="9" height="22" rx="2" fill="currentColor" opacity="0.55"/><rect x="23" y="9" width="9" height="22" rx="2" fill="currentColor"/>`,
  },

  // ── Infrastructure / APIs ──
  plaid: {
    color: "#0F6FFF",
    svg: `<rect x="7" y="7" width="26" height="26" rx="3" fill="none" stroke="currentColor" stroke-width="2.6"/><path d="M12 13h16M12 20h16M12 27h10M30 27h-2" stroke="currentColor" stroke-width="2.4" stroke-linecap="round"/>`,
  },
  marqeta: {
    color: "#00C6FF",
    svg: `<rect x="6" y="12" width="28" height="16" rx="3" fill="none" stroke="currentColor" stroke-width="2.6"/><path d="M6 18h28" stroke="currentColor" stroke-width="2.6"/><circle cx="14" cy="22" r="2" fill="currentColor"/>`,
  },
  synapse: {
    color: "#037BF5",
    svg: `<circle cx="20" cy="14" r="4" fill="currentColor"/><circle cx="13" cy="26" r="3" fill="currentColor"/><circle cx="27" cy="26" r="3" fill="currentColor"/><path d="M20 14l-7 12M20 14l7 12M13 26h14" stroke="currentColor" stroke-width="2" fill="none"/>`,
  },
  galileo: {
    color: "#0077CC",
    svg: `<circle cx="20" cy="20" r="10" fill="none" stroke="currentColor" stroke-width="2.6"/><circle cx="20" cy="20" r="4" fill="currentColor"/><path d="M20 6v8M20 26v8M6 20h8M26 20h8" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>`,
  },
  unit: {
    color: "#5334F7",
    svg: `<rect x="6" y="6" width="28" height="28" rx="6" fill="currentColor"/><path d="M14 14v9h6c3 0 5-2 5-5s-2-5-5-5h-6z" fill="#fff"/><path d="M14 23v5" stroke="#fff" stroke-width="3" stroke-linecap="round"/>`,
  },
  rapyd: {
    color: "#5C38FF",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M20 13v14M13 20h14" stroke="#fff" stroke-width="3" stroke-linecap="round" opacity="0.5"/>`,
  },

  // ── Spend Management ──
  ramp: {
    color: "#FFD600",
    bg: "#1A1A1A",
    svg: `<rect x="5" y="5" width="30" height="30" rx="6" fill="#1A1A1A"/><path d="M11 14l9 6 9-6v8l-9 6-9-6z" fill="#FFD600"/>`,
  },
  brex: {
    color: "#FF5C00",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M14 12v16M14 12h9c3 0 5 2 5 5s-2 5-5 5H14M14 22h9c3 0 5 1 5 4" stroke="#fff" stroke-width="2.8" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  mercury: {
    color: "#E5E5E5",
    bg: "#1F1F1F",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="#1F1F1F"/><circle cx="20" cy="20" r="11" fill="none" stroke="#E5E5E5" stroke-width="2.6"/><path d="M9 18h22M9 22h22" stroke="#E5E5E5" stroke-width="2" opacity="0.5"/><ellipse cx="20" cy="20" rx="6" ry="11" fill="none" stroke="#E5E5E5" stroke-width="1.4" opacity="0.7"/>`,
  },
  divvy: {
    color: "#FF5C58",
    svg: `<rect x="6" y="9" width="28" height="22" rx="4" fill="none" stroke="currentColor" stroke-width="2.6"/><rect x="13" y="22" width="14" height="3" rx="1" fill="currentColor"/>`,
  },
  airbase: {
    color: "#1B9DF9",
    svg: `<circle cx="20" cy="20" r="13" fill="none" stroke="currentColor" stroke-width="3"/><path d="M13 18l4 4 6-7 4 4" stroke="currentColor" stroke-width="2.4" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },

  // ── Lending ──
  lendingclub: {
    color: "#00853E",
    svg: `<circle cx="20" cy="20" r="13" fill="none" stroke="currentColor" stroke-width="3"/><path d="M14 14l6 6 6-6M20 20v8" stroke="currentColor" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  upstart: {
    color: "#00B07C",
    svg: `<path d="M12 28l8-16 8 16" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><circle cx="20" cy="10" r="3" fill="currentColor"/>`,
  },
  ondeck: {
    color: "#0096D6",
    svg: `<rect x="6" y="6" width="28" height="28" rx="4" fill="currentColor"/><ellipse cx="20" cy="20" rx="11" ry="7" fill="none" stroke="#fff" stroke-width="2.4"/>`,
  },
  avant: {
    color: "#4962E2",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M20 11v9l7 4" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round"/>`,
  },
  prosper: {
    color: "#F2691B",
    svg: `<circle cx="20" cy="20" r="13" fill="none" stroke="currentColor" stroke-width="3"/><path d="M14 14l12 12M26 14L14 26" stroke="currentColor" stroke-width="2.4" stroke-linecap="round"/>`,
  },

  // ── Payroll & HR ──
  gusto: {
    color: "#F45D48",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M14 16c2-3 6-3 8 0 2 3 6 3 8 0" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round"/>`,
  },
  deel: {
    color: "#0BE1C1",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="#0B232C"/><path d="M14 12c6-3 12 3 6 8-3 3-6 8-6 8s3-5 6-8c2-2 4-5 2-8z" fill="#0BE1C1"/>`,
  },
  rippling: {
    color: "#15B6FF",
    svg: `<circle cx="20" cy="20" r="3" fill="currentColor"/><circle cx="20" cy="20" r="7" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="20" cy="20" r="11" fill="none" stroke="currentColor" stroke-width="2" opacity="0.6"/>`,
  },
  remote: {
    color: "#00A8E8",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M14 14c4 4 8 4 12 0M14 26c4-4 8-4 12 0" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round"/>`,
  },
  "papaya-global": {
    color: "#FF8A00",
    svg: `<ellipse cx="20" cy="14" rx="9" ry="6" fill="currentColor"/><ellipse cx="20" cy="26" rx="9" ry="6" fill="currentColor" opacity="0.6"/>`,
  },
  adp: {
    color: "#D0271C",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><text x="20" y="25" text-anchor="middle" font-family="monospace" font-size="11" font-weight="700" fill="#fff">ADP</text>`,
  },
  paychex: {
    color: "#003594",
    svg: `<rect x="6" y="6" width="28" height="28" rx="5" fill="currentColor"/><path d="M13 22h14M16 18h8M16 26h8" stroke="#fff" stroke-width="2.3" stroke-linecap="round" opacity="0.9"/>`,
  },

  // ── Identity & Fraud ──
  sumsub: {
    color: "#FF5C00",
    svg: `<circle cx="20" cy="11" r="5" fill="currentColor"/><path d="M11 30a9 9 0 0118 0z" fill="currentColor"/><path d="M16 11l4 4 8-9" stroke="#fff" stroke-width="2.2" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  onfido: {
    color: "#7856FF",
    svg: `<circle cx="20" cy="14" r="5" fill="currentColor"/><path d="M11 30a9 9 0 0118 0z" fill="currentColor" opacity="0.85"/>`,
  },
  socure: {
    color: "#5C38FF",
    svg: `<circle cx="20" cy="20" r="13" fill="none" stroke="currentColor" stroke-width="3"/><path d="M14 16l3 4 6 1-5 2v2l-4-3-4-1z" fill="currentColor"/>`,
  },
  sift: {
    color: "#5A43F7",
    svg: `<path d="M11 9h18l-4 11h4l-4 11H11l4-11h-4z" fill="currentColor"/>`,
  },
  forter: {
    color: "#7A3FF7",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M13 20l5 5 8-9" stroke="#fff" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },

  // ── Insurtech ──
  lemonade: {
    color: "#FFD900",
    bg: "#FF4081",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="#FF4081"/><path d="M20 11l6 4v6c0 4-3 6-6 7-3-1-6-3-6-7v-6z" fill="#FFD900"/><path d="M17 21l2 2 4-4" stroke="#FF4081" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  hippo: {
    color: "#13A554",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M13 16h4v3h6v-3h4v9h-4v-4H17v4h-4z" fill="#fff"/>`,
  },
    oscar: {
    color: "#009E5E",
    svg: `<circle cx="20" cy="20" r="13" fill="none" stroke="currentColor" stroke-width="3"/><path d="M14 14l4 4M26 26l-4-4M14 26l4-4M26 14l-4 4" stroke="currentColor" stroke-width="2.4" stroke-linecap="round"/>`,
  },
  "next-insurance": {
    color: "#0066FF",
    svg: `<rect x="5" y="5" width="30" height="30" rx="6" fill="currentColor"/><path d="M20 11l8 3v6c0 5-4 8-8 9-4-1-8-4-8-9v-6z" stroke="#fff" stroke-width="2.4" fill="none" stroke-linejoin="round"/>`,
  },

  // ── PropTech ──
  "better-com": {
    color: "#017EFD",
    svg: `<path d="M8 22l12-10 12 10v8H8z" fill="currentColor"/><path d="M16 30v-6h8v6" stroke="#fff" stroke-width="2.4" fill="none" stroke-linejoin="round"/>`,
  },
  "rocket-mortgage": {
    color: "#C8102E",
    svg: `<path d="M8 22l12-10 12 10" fill="currentColor"/><path d="M13 20v10h14V20" stroke="#C8102E" stroke-width="2.4" fill="none" stroke-linejoin="round"/><circle cx="20" cy="11" r="2" fill="#C8102E"/>`,
  },
  opendoor: {
    color: "#00BA6C",
    svg: `<rect x="12" y="8" width="16" height="24" rx="2" fill="currentColor"/><path d="M14 10h12v20H14z" stroke="#fff" stroke-width="1.5" fill="none"/><circle cx="23" cy="20" r="1.5" fill="#fff"/>`,
  },
  blend: {
    color: "#5C38FF",
    svg: `<circle cx="20" cy="20" r="13" fill="none" stroke="currentColor" stroke-width="3"/><path d="M13 13h14v14H13z" fill="currentColor" opacity="0.2"/><path d="M13 27L27 13" stroke="currentColor" stroke-width="2.4" stroke-linecap="round"/>`,
  },

  // ── Additional brand marks (new entries) ──
  "cash-app": {
    color: "#00D54B",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M20 9v22M14 15h12c2 0 4 1 4 3s-2 3-4 3H14" stroke="#0a0a0a" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  venmo: {
    color: "#008CFF",
    svg: `<circle cx="20" cy="20" r="14" fill="currentColor"/><path d="M33 11l-8 24-6-15-6 15-5-24" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  "apple-pay": {
    color: "#FFFFFF",
    bg: "#000000",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="#000"/><path d="M18 11c2-1.5 3-2.5 3-5 0-.5 0-.5 1-.5 3 0 7 4 7 8 0 5-3 8-7 8-2.5 0-4-1-5-1s-2.5 1-5 1c-3 0-6-4-6-9 0-3 2-6 5-8l2-1 2.5 2.5c1.5 1.5 2.5 3 2.5 3z" fill="#fff"/>`,
  },
  "google-pay": {
    color: "#4285F4",
    svg: `<rect x="6" y="6" width="28" height="28" rx="6" fill="currentColor"/><path d="M26 14h-6v5h6v-2.5h-4V16h4M16 14h-2v7h2M20 19l-3 2v-3.5l-2-1.5 3-2z" stroke="#fff" stroke-width="1.8" fill="none" stroke-linecap="round" stroke-linejoin="round"/><rect x="14" y="11" width="12" height="10" rx="2" stroke="#4285F4" stroke-width="1.2" fill="none"/>`,
  },
  "visa-direct": {
    color: "#1A1F71",
    svg: `<rect x="5" y="5" width="30" height="30" rx="4" fill="currentColor"/><path d="M13 26V14l-2 6-3-6v12M22 26V16h-2v-2l4-2v14M33 26L27 14l-3 12" stroke="#fff" stroke-width="2.2" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  "mastercard-send": {
    color: "#EB001B",
    svg: `<circle cx="14" cy="20" r="9" fill="#EB001B" opacity="0.95"/><circle cx="26" cy="20" r="9" fill="#F79E1B" opacity="0.9"/><circle cx="20" cy="20" r="4" fill="none" stroke="#fff" stroke-width="2" opacity="0.6"/><path d="M14 24h12M14 16h12" stroke="#fff" stroke-width="1.4" opacity="0.35"/>`,
  },
  upgrade: {
    color: "#00B2A9",
    svg: `<path d="M20 7c-7 0-11 4-11 10s5 10 11 10 11-4 11-10" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><circle cx="20" cy="17" r="4" fill="currentColor"/><path d="M16 13l8-6" stroke="currentColor" stroke-width="3" stroke-linecap="round"/>`,
  },
  dave: {
    color: "#22C55E",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M12 20c3 5 6 5 8 3 2 2 4 2 7-3" stroke="#000" stroke-width="2.6" fill="none" stroke-linecap="round"/>`,
  },
  moneylion: {
    color: "#00C2A9",
    svg: `<path d="M28 23L20 12l-8 11h6v7h4v-7z" fill="currentColor"/><circle cx="14" cy="22" r="1.8" fill="currentColor"/><circle cx="27" cy="22" r="1.8" fill="currentColor"/>`,
  },
  greenlight: {
    color: "#00CC44",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M14 15h12v10H14z" fill="#fff"/><circle cx="20" cy="20" r="3" fill="currentColor"/>`,
  },
  "modern-treasury": {
    color: "#0F1726",
    svg: `<rect x="6" y="6" width="28" height="28" rx="4" fill="currentColor"/><path d="M10 18h20M10 24h12M10 30h16" stroke="#38BDF8" stroke-width="2.4" stroke-linecap="round"/>`,
  },
  increase: {
    color: "#08E296",
    svg: `<rect x="6" y="6" width="28" height="28" rx="8" fill="currentColor"/><path d="M13 14h14M13 20h14" stroke="#0a0a0a" stroke-width="2.6" stroke-linecap="round"/>`,
  },
  bond: {
    color: "#4800FF",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M28 12L12 28M28 28L12 12" stroke="#fff" stroke-width="2.6" stroke-linecap="round"/>`,
  },
  kraken: {
    color: "#5741D9",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M20 13l5 10-5-3-5 3z" fill="#fff"/><path d="M20 13v10" stroke="#fff" stroke-width="1.8" stroke-linecap="round"/>`,
  },
  "ig-group": {
    color: "#EB1C2A",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><text x="20" y="25" text-anchor="middle" font-family="monospace" font-weight="700" font-size="14" fill="#fff">IG</text>`,
  },
  melio: {
    color: "#1579FB",
    svg: `<rect x="6" y="6" width="28" height="28" rx="6" fill="currentColor"/><path d="M14 14h12M14 20h12" stroke="#fff" stroke-width="2.4" stroke-linecap="round"/><rect x="13" y="13" width="14" height="2" rx="1" fill="#fff"/>`,
  },
  freshbooks: {
    color: "#0075DD",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M20 13l6 2v14H14z" fill="#fff" opacity="0.95"/><path d="M20 13l6 2" stroke="#0075DD" stroke-width="1" fill="none"/>`,
  },
  taxact: {
    color: "#00A85A",
    svg: `<rect x="6" y="6" width="28" height="28" rx="6" fill="currentColor"/><text x="20" y="25" text-anchor="middle" font-family="monospace" font-weight="700" font-size="11" fill="#fff">TAX</text>`,
  },

  // ── Inline entries for prominent null brands (previously monogram-only) ──
  // Hand-drawn geometric marks inspired by each brand's visual identity.
  // These are NOT 1:1 logo copies — they read as brand-recognizable marks.
  airwallex: {
    color: "#00B8A9",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M20 7v26M11 14h18M11 26h18" stroke="#fff" stroke-width="2.4" stroke-linecap="round" opacity="0.85"/>`,
  },
  nium: {
    color: "#005CFF",
    svg: `<rect x="6" y="6" width="28" height="28" rx="7" fill="currentColor"/><path d="M14 26V14h4l8 12h-4l-8-12M22 14h6" stroke="#fff" stroke-width="2.4" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  dlocal: {
    color: "#00CD91",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M14 20l5 5 9-10" stroke="#fff" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  ebanx: {
    color: "#00A3E0",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><text x="20" y="26" text-anchor="middle" font-family="monospace" font-weight="700" font-size="13" fill="#fff">e</text>`,
  },
  qonto: {
    color: "#00A4FF",
    svg: `<rect x="5" y="5" width="30" height="30" rx="8" fill="currentColor"/><path d="M11 14l9 14h-4l-9-14z" fill="#fff"/><circle cx="26" cy="26" r="2.5" fill="#fff"/>`,
  },
  "trade-republic": {
    color: "#3D2DE6",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M14 14v10l4-6 4 6V14M22 14v6h3M22 18h3" stroke="#fff" stroke-width="2.4" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  oaknorth: {
    color: "#6F2DE6",
    svg: `<path d="M20 6l12 7v10l-12 8-12-8V13z" fill="currentColor"/><path d="M16 17v6l4 3 4-3v-6l-4-2z" fill="#fff"/>`,
  },
  monese: {
    color: "#52338C",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M14 20l4-7h4l-4 7h4l-4 7" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  vanta: {
    color: "#6F2DF5",
    svg: `<circle cx="20" cy="20" r="13" fill="none" stroke="currentColor" stroke-width="3"/><path d="M20 10l3 4-3 6-3-6zM10 22l3 4 3-6-3-6zM30 22l-3 4-3-6 3-6z" stroke="currentColor" stroke-width="2.4" fill="currentColor" stroke-linejoin="round"/>`,
  },
  mambu: {
    color: "#0CB6AD",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M14 14v12M14 20l10-6" stroke="#0a0a0a" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  trulioo: {
    color: "#1A75FF",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M11 20a9 9 0 0018 0" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round"/><circle cx="14" cy="14" r="2" fill="#fff"/><circle cx="26" cy="14" r="2" fill="#fff"/>`,
  },
  thunes: {
    color: "#0066FF",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M11 26l9-10 4 3 5-7v12" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  ppro: {
    color: "#005EB8",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><text x="20" y="26" text-anchor="middle" font-family="monospace" font-weight="700" font-size="14" fill="#fff">P</text>`,
  },
  shift4: {
    color: "#0A2540",
    svg: `<rect x="5" y="5" width="30" height="30" rx="6" fill="currentColor"/><path d="M14 14v12M14 20l8-6M22 14l4 12" stroke="#5EEAD4" stroke-width="2.8" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  bitpanda: {
    color: "#22C8A0",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><circle cx="20" cy="20" r="5" fill="#fff"/><circle cx="20" cy="20" r="1.5" fill="currentColor"/>`,
  },
  toss: {
    color: "#0064FF",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M14 12c0 6 4 10 6 10s6-4 6-10" stroke="#fff" stroke-width="3" fill="none" stroke-linecap="round"/>`,
  },
  "cross-river": {
    color: "#0057B8",
    svg: `<path d="M6 18c6-8 22-8 28 0v6c-6-4-22-4-28 0z" fill="currentColor"/><path d="M6 26c6-4 22-4 28 0" stroke="currentColor" stroke-width="2.4" fill="none"/>`,
  },
  column: {
    // Two-bar mark in near-black vanishes on the dark tile; pin to white.
    color: "#2D2D2D",
    bg: "#ffffff",
    svg: `<rect x="12" y="6" width="6" height="28" rx="1.5" fill="currentColor" opacity="0.4"/><rect x="22" y="6" width="6" height="28" rx="1.5" fill="currentColor"/>`,
  },
  "lead-bank": {
    color: "#111111",
    svg: `<rect x="5" y="5" width="30" height="30" rx="6" fill="currentColor"/><path d="M14 21l6-7 6 7v6h-12z" fill="#fff"/>`,
  },
  gemini: {
    color: "#00DCFA",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><circle cx="15" cy="20" r="3.5" fill="#fff"/><circle cx="25" cy="20" r="3.5" fill="#fff"/><path d="M18.5 20h3" stroke="#fff" stroke-width="1.6"/>`,
  },
  bybit: {
    color: "#F7A800",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M12 14l8 6-8 6V14M20 14v12l8-6z" fill="#0a0a0a"/>`,
  },
  bitstamp: {
    color: "#00B4EF",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M14 14h12v12H14z" fill="#fff"/><circle cx="20" cy="20" r="3" fill="currentColor"/>`,
  },
  ledger: {
    color: "#142533",
    svg: `<rect x="9" y="9" width="22" height="22" rx="2" fill="currentColor"/><rect x="13" y="13" width="14" height="10" rx="1" fill="#fff"/><rect x="17" y="25" width="6" height="1.4" rx="0.6" fill="#fff"/><rect x="17" y="28" width="6" height="1.4" rx="0.6" fill="#fff"/>`,
  },
  fireblocks: {
    color: "#FB923C",
    svg: `<circle cx="20" cy="20" r="9" fill="currentColor"/><circle cx="20" cy="20" r="4" fill="#fff"/><path d="M11 20h18M20 11v18" stroke="currentColor" stroke-width="2" opacity="0.45" stroke-dasharray="2 2"/>`,
  },
  "anchorage-digital": {
    color: "#1E4DDB",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M20 7l4 7-4 4-4-4z M12 26l4-4 4 4-4 4z M28 26l-4-4 4-4 4 4z" fill="#fff"/>`,
  },
  kakaobank: {
    color: "#FFDD00",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><text x="20" y="26" text-anchor="middle" font-family="monospace" font-weight="700" font-size="15" fill="#0a0a0a">K</text>`,
  },
  wefox: {
    color: "#5C2D91",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M11 22a9 9 0 0118 0 9 9 0 01-18 0" fill="#fff"/><circle cx="20" cy="22" r="3.5" fill="currentColor"/><circle cx="14" cy="12" r="2" fill="#fff"/><circle cx="26" cy="12" r="2" fill="#fff"/>`,
  },
  "mesh-payments": {
    color: "#00C16E",
    svg: `<circle cx="13" cy="14" r="4" fill="currentColor"/><circle cx="27" cy="14" r="4" fill="currentColor" opacity="0.7"/><circle cx="20" cy="26" r="4" fill="currentColor" opacity="0.4"/><path d="M13 14l7 12M27 14l-7 12" stroke="currentColor" stroke-width="2" opacity="0.7"/>`,
  },
  vivid: {
    color: "#FF2E63",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M11 14h6v6l4-6h6l-6 8 6 8h-6l-4-6v6h-6z" fill="#fff"/>`,
  },
  omnipresent: {
    color: "#1E3A8A",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><circle cx="20" cy="20" r="9" fill="none" stroke="#fff" stroke-width="2"/><circle cx="20" cy="20" r="3" fill="#fff"/>`,
  },

  // ── Final monogram-ectomy rounds ──
  "amazon-pay": {
    color: "#FF9900",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M14 22c4 4 8 4 12 0" stroke="#0a0a0a" stroke-width="2.6" fill="none" stroke-linecap="round"/><path d="M16 18l2-2 2 2-2 2z" fill="#0a0a0a"/>`,
  },
  "best-egg": {
    color: "#FFA436",
    svg: `<ellipse cx="20" cy="20" rx="13" ry="9" fill="currentColor"/><path d="M14 17l6 3 6-3M14 23l6 3 6-3" stroke="#0a0a0a" stroke-width="1.8" fill="none" stroke-linecap="round"/>`,
  },
  clearbank: {
    color: "#005EB8",
    svg: `<rect x="5" y="5" width="30" height="30" rx="6" fill="currentColor"/><path d="M14 14h12v3H21l-2 3 2 3v3h-2v-3h-5z" fill="#fff"/>`,
  },
  factorial: {
    color: "#0F0F0F",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M14 26V14c0-3 2-5 5-5h2M14 26l9-12" stroke="#FFCB05" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  gr4vy: {
    color: "#FF6C38",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M11 17l6 4 6-4M11 23l6 4 6-4" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  "green-dot": {
    color: "#00A651",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><circle cx="20" cy="20" r="5" fill="#fff"/>`,
  },
  griffin: {
    color: "#000000",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M14 22l6-8 6 8zM14 24h12" stroke="#FFD700" stroke-width="2.4" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  lendable: {
    color: "#FF5C00",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M14 14h12M14 20h12M14 26h6" stroke="#fff" stroke-width="2.6" stroke-linecap="round"/>`,
  },
  multiplier: {
    color: "#2DDBBE",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M20 8v24M8 20h24M11 11l18 18M29 11L11 29" stroke="#0a0a0a" stroke-width="2.2" stroke-linecap="round"/>`,
  },
  oyster: {
    color: "#00707C",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><circle cx="20" cy="20" r="6" fill="#fff"/><circle cx="20" cy="20" r="2.5" fill="currentColor"/>`,
  },
  "root-insurance": {
    color: "#17A6C9",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M20 7l10 6v9c0 5-4 8-10 11-6-3-10-6-10-11v-9l10-6z" fill="#fff"/><path d="M14 20l4 4 8-8" stroke="currentColor" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  "scalable-capital": {
    color: "#00B9A9",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M12 26l4-12 3 6 3-6 4 12" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  stax: {
    color: "#0A2540",
    svg: `<rect x="5" y="5" width="30" height="30" rx="6" fill="currentColor"/><path d="M11 14h18v8H11zM11 24h18M11 28h12" stroke="#5EEAD4" stroke-width="2.4" stroke-linecap="round"/>`,
  },
  "trading-212": {
    color: "#26D07C",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M14 14l4 12 4-12M14 14h8M14 26h8" stroke="#0a0a0a" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  "uniswap-labs": {
    color: "#FF007A",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M14 20l4 4 8-8" stroke="#fff" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round"/><circle cx="20" cy="20" r="3" fill="#fff"/>`,
  },
  "velocity-global": {
    color: "#5B2C91",
    svg: `<circle cx="20" cy="20" r="13" fill="currentColor"/><path d="M11 26l8-12 4 4 6-8" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
  workmotion: {
    color: "#FF3366",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M20 7v26M7 20h26" stroke="#fff" stroke-width="2.6" stroke-linecap="round"/>`,
  },
  zopa: {
    color: "#800080",
    svg: `<rect x="5" y="5" width="30" height="30" rx="7" fill="currentColor"/><path d="M11 20l7-7 4 4 7-7M11 20l7 7 4-4 7 7" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`,
  },
};

/**
 * A single accessible image semantic per logo:
 * - Non-decorative: outer span is `role="img"` labelled with the company name;
 *   the inner <img>/SVG is `aria-hidden` (no nested/redundant names).
 * - decorative (e.g. a logo used purely as a visual accent): the whole mark is
 *   `aria-hidden` and not announced.
 */
export function CompanyLogo({
  slug,
  name,
  size = 48,
  decorative = false,
}: {
  slug: string;
  name?: string;
  size?: number;
  decorative?: boolean;
}) {
  const imgLabel = `${name ?? slug} logo`;
  const hiddenAria = decorative
    ? { "aria-hidden": true as const }
    : { role: "img" as const, "aria-label": imgLabel };
  // ── Tier 1: real official mark (downloaded from simple-icons) ──
  const real = REAL_LOGOS[slug];
  if (real) {
    // outerBg: explicit brand surface wins (Apple Pay black, Wise green,
    // Klarna pink). Light-fill marks get a white inset. Everything else sits
    // on a neutral `--surface-raised` tile for catalog consistency.
    let outerBg = "var(--surface-raised)";
    let tileBorder = "var(--border-color)";
    if (real.bg) {
      outerBg = real.bg;
      tileBorder = "transparent";
    } else if (real.tile === "light") {
      outerBg = "#ffffff";
    }
    const pad = Math.max(5, Math.round(size * 0.16));

    return (
      <span
        className="inline-flex items-center justify-center rounded-xl overflow-hidden shrink-0 transition-transform duration-300 group-hover:scale-105"
        {...hiddenAria}
        style={{
          width: size,
          height: size,
          background: outerBg,
          border: `1px solid ${tileBorder}`,
        }}
      >
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={`/logos/${slug}.svg`}
          alt=""
          aria-hidden="true"
          width={size - pad * 2}
          height={size - pad * 2}
          loading="lazy"
          decoding="async"
          style={{
            display: "block",
            width: size - pad * 2,
            height: size - pad * 2,
            objectFit: "contain",
          }}
        />
      </span>
    );
  }

  // ── Tier 2: hand-drawn inline approximation ──
  const s = logoShapes[slug];
  if (!s) {
    // Monogram fallback for any slug with neither a real logo nor a shape.
    const monogram = slug
      .split(/[-_]/)
      .map((w) => w[0])
      .join("")
      .slice(0, 2)
      .toUpperCase();
    return (
      <span
        className="inline-flex items-center justify-center rounded-xl bg-[var(--surface-raised)] font-mono font-bold uppercase tracking-wider text-[var(--foreground)] border border-[var(--border-color)]"
        {...hiddenAria}
        style={{ width: size, height: size, fontSize: Math.max(10, size * 0.32) }}
      >
        {monogram}
      </span>
    );
  }

  // Brand-correct surfaces get their own colored tile (Wise green, Ramp black,
  // Mercury graphite, Zip/Column white). Other marks sit on a neutral
  // `--surface-raised` tile so they read cleanly across the whole dark catalog.
  const isBrandedSurface = !!s.bg;
  const tileBg = isBrandedSurface ? (s.bg as string) : "var(--surface-raised)";
  const tileBorder = isBrandedSurface ? "transparent" : "var(--border-color)";
  // Resolve `currentColor` inside the inline SVG to the brand color regardless
  // of tile. The older branded-surface marks (wise, ramp, mercury, deel…)
  // hardcode their path colours and ignore currentColor, so this is a no-op for
  // them; currentColor-based marks (zip, column) keep their intended ink colour
  // instead of inheriting the page foreground.
  const markColor = s.color ?? "currentColor";
  const pad = Math.max(4, Math.round(size * 0.14));
  const inner = size - pad * 2;

  return (
    <span
      className="inline-flex items-center justify-center rounded-xl overflow-hidden shrink-0 transition-transform duration-300 group-hover:scale-105"
      {...hiddenAria}
      style={{
        width: size,
        height: size,
        backgroundColor: tileBg,
        border: `1px solid ${tileBorder}`,
        color: markColor,
      }}
      dangerouslySetInnerHTML={{
        __html: `<svg width="${inner}" height="${inner}" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg" style="color:${markColor}">${s.svg}</svg>`,
      }}
    />
  );
}
